title: Tracking the SolarWinds Hack

description: Tracking and documenting the many storylines in the SolarWinds hack

show_excerpts: true 

# For the footer of blog pages
github_username: r-dube
rss: rss

# for rss
url: https://r-dube.github.io

# For comments on posts
disqus:
    shortname: solarwinds

# Github pages Jekyll theme
theme: minima

# For the RSS button and feed.xml
plugins:
 - jekyll-feed
